name: Update Lines of Code

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  push:
    branches:
      - main  # Run workflow on push to the main branch

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cloc jq

      - name: Calculate Lines of Code
        run: cloc --json . > cloc.json

      - name: Get Lines of Code
        id: loc
        run: |
          LINES=$(jq .SUM.code cloc.json)
          echo "lines=$LINES" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s|<!-- lines-of-code -->|<!-- lines-of-code -->\n![Lines of code](https://img.shields.io/badge/From%20Hello%20World%20I%27ve%20Written-$LINES%20lines%20of%20code-blue)|" README.md
        env:
          CODE_GITHUB_TOKEN: ${{ secrets.CODE_GITHUB_TOKEN }}
          LINES: ${{ steps.loc.outputs.lines }}
